### ISSUE TITLE
打开开始菜单时，屏幕下半部分的圆角消失

### ISSUE THREAD

**Issue by BananaTennise** [PlayForm/Round#157]
每次打开开始菜单时，屏幕下半部分的圆角消失，
Windows版本 Windows11 22631.3155

**Comment by NikolaRHristov** [comment]
感谢您的报告。不幸的是，这个问题无法解决，因为 Windows 将任务栏置于顶部并全屏显示，从而覆盖了应用程序。我会寻找更多解决方案，但目前不支持

**Comment by bitchbaddass** [comment]
当电脑休眠后重新启动时，屏幕下半部分圆角会一直保持消失状态
