### ISSUE TITLE
There is no singleton mode. It is recommended to optimize it.

### ISSUE THREAD

**Issue by Zander-1024** [PlayForm/Round#25]

**Comment by NikolaRHristov** [comment]
Hi, can you elaborate? Singleton meaning display on only one monitor?

**Comment by Zander-1024** [comment]
Only one use case is started. When the software is started repeatedly, it will be detected whether there is such a use case. If there is, it will not be created repeatedly.

**Comment by NikolaRHristov** [comment]
I'm not sure I understand, you want the program to only be executable once?

**Comment by Zander-1024** [comment]
Only a single instance is retained. Instead of having multiple instances

**Comment by NikolaRHristov** [comment]
You can have multiple instances.

**Comment by Zander-1024** [comment]
Isn't a single instance enough? Why create multiple duplicate instances?

**Comment by NikolaRHristov** [comment]
I don't want to limit the application on how many times it can launch. If you want only one application running, launch just one.
