### ISSUE TITLE
Binary release?

### ISSUE THREAD

**Issue by ilovefreesw** [PlayForm/Round#5]
Is there a plan to push a binary release for it ? because setting up Rust toolchain for it will be a quite exhausting.

**Comment by NikolaRHristov** [comment]
Binary releases were removed because the app was shortly offline.

**Comment by NikolaRHristov** [comment]
They will be up shortly!

**Comment by NikolaRHristov** [comment]
Fixed in https://github.com/RoundedCorners/app/releases/tag/v0.0.8
